spring.application.name=llmmemory
spring.ai.openai.api-key=${GROQ-API-KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.chat.model=openai/gpt-oss-120b
spring.ai.openai.chat.model=groq/compound-mini


